id: P44BB4EBB
initial_creation_type: input
source_metadata:
  title: Shechen Gyaltsab Gyurme Pema Namgyal
  language: fr
  description: 'Texts by and about Shechen Gyatsab Gyurme Pema Namgyal (zhe chen rgyal
    tshab ''gyur med padma rnam rgyal, 1871–1926):'
  volume:
    7a5da7b2029c4b67959496794fa61cd2:
      title: Advice for Gelong Jampa Dargye
      parent: Advice
    869ef5a8e1b549e6a1065700568540c1:
      title: A Prayer of Aspiration
      parent: Aspiration Prayers
    33aee4ae86534a3890ac57203066b2bc:
      title: Lamp Aspiration Prayer
      parent: Aspiration Prayers
    a73996ef63964e888022b772bdfded95:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    6456f6204b3a4f2d92740aa4f40f418b:
      title: Brief Offering Prayer to Gesar
      parent: Dharma Protectors
    72415d06e1bd4538b605d4648b474210:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Dharma Protectors
    eee2bf39808d435d892bfa2bd42f81c1:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Guru Yoga
    0386987498514aedb929cc8d43985b4b:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    2c6fce9325104f29bec2b7acf5e52946:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Long Life Prayers
    70e51288b4f24d3cb811738145aa181e:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    299d3186e2f2475ab47e68cc9389c837:
      title: A Prayer To Padmasambhava
      parent: Prayers
    8850d43710c24e6c97409266425a0ded:
      title: A Prayer to Amitāyus
      parent: Prayers
    4ec6f83d977a4cc49c6f9da2aa6c109d:
      title: A Prayer to Mañjughoṣa
      parent: Prayers
    9b34cfa8678144b3b7177b52daed3d18:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Prayers
    3bb51b952d3741cda1f31b539d9e5b2f:
      title: A Concise Feast Prayer
      parent: Tsok
created_at: '2022-03-01T01:34:05.452595'
last_modified_at: '2022-03-01T01:34:05.452598'
